sudo: required
jdk:
- oraclejdk8
language: java
install: travis_wait mvn -q install -U -DskipTests=true
after_success:
- ci/deploy_snapshot.sh
- ci/publish-javadoc-to-gh-pages.sh
branches:
  except:
  - gh-pages
addons:
  sonarcloud:
    organization: cloudiator
    token:
      secure:
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
notifications:
  slack:
    secure:
